### PR TITLE
Fix/navbar

### PR DESCRIPTION
**Pull request by yeikiu**

### CODE REVIEW

**Comment by MSoup** [comment]
Thanks for the pull request!

There are a few issues I've noticed:

1. In the desktop view, the changes have broken the navigation. I'm able to highlight the sections (all, guide, features) and confirm that they are indeed <a> links, but something is blocking them from being clicked. (I haven't looked into it yet)

2. In the mobile view, everything works as expected until the user has navigated to a link. After navigating, the hamburger icon requires two clicks in order to display the dropdown. It seems the first click adds `class="navbar-collapse collapse"` along with various other triggers, but visually nothing is happening. The second click finally brings it up.

This is a little trickier than I thought it would be :)

**Comment by yeikiu** [comment]
> Thanks for the pull request!
> 
> There are a few issues I've noticed:
> 
> 1. In the desktop view, the changes have broken the navigation. I'm able to highlight the sections (all, guide, features) and confirm that they are indeed  links, but something is blocking them from being clicked. (I haven't looked into it yet)
> 2. In the mobile view, everything works as expected until the user has navigated to a link. After navigating, the hamburger icon requires two clicks in order to display the dropdown. It seems the first click adds `class="navbar-collapse collapse"` along with various other triggers, but visually nothing is happening. The second click finally brings it up.
> 
> This is a little trickier than I thought it would be :)

Yes this seems to be a bit trickier than expected. I found a few good suggestions under this SO thread: https://stackoverflow.com/questions/36170425/detect-click-outside-element but don't have much time to dedicate to debugging rn. I will keep the PR open in case someone feels like contributing.

If you are looking for the best platform to develop this kind of blog nowadays I'd probably suggest going with deno/fresh I might redo this same idea with MD+tailwind under that stack soon...

**Comment by yeikiu** [comment]
I've just committed a version which simplifies a lot the NavBar logic and works in both mobile and desktop locally.

I'd appreciate if you can test and approve the PR :)

**Comment by MSoup** [comment]
Sorry for the slow reply. I just got around to looking at it. The functionality seems pretty good! There's a few things that Vue is yelling at us about in the console, though, so I'll further clean it up since others will inevitably use this :)

`collapseMenu` no longer exists, but there are a few references to it. I will go ahead and remove these, and then I'll peek around for other things we may have missed.

**Comment by yeikiu** [comment]
Hey man!

That's totally ok, great to see people collaborating on improving open
source.

I reviewed my branch and there were no references to *collapseMenu *in
there. Only as aria labels which should not affect functionality.
[image: Screenshot 2023-01-18 at 12.49.08.png]

Latest version has been released and it shines more than ever thanks to
your additions 🙂

Kudos!

**Comment by MSoup** [comment]
Oh, strange.. that means I might have completely butchered the merge locally and committed it. I hope I didn't break anything! Thanks a lot for collaborating with me. I'm very new to development, so I appreciate your patience haha

**Comment by yeikiu** [comment]
All good and working.

You should be proud if you are already collaborating at this level being relatively new to the dev world!

**Pull request merged**
